package view.customer;

/**
 *
 * @author Arith Alexis Villalba Bravo
 * @date 9/05/2016
 * @time 11:13:11 PM
 */
public class CustomerView extends javax.swing.JInternalFrame {

    public CustomerView() {
        initComponents();
    }

    public javax.swing.JLabel getLblTittleRegister() {
        return lblTittleRegister;
    }

    public javax.swing.JLabel getLblWarning() {
        return lblWarning;
    }

    public javax.swing.JLabel getLblWarning1() {
        return lblWarning1;
    }

    public javax.swing.JLabel getLblWarning2() {
        return lblWarning2;
    }

    public javax.swing.JLabel getLblWarning3() {
        return lblWarning3;
    }

    public javax.swing.JLabel getLblWarning4() {
        return lblWarning4;
    }

    public javax.swing.JPanel getPnlRegister() {
        return pnlRegister;
    }

    public javax.swing.JPanel getPnlCustomers() {
        return pnlCustomers;
    }

    public javax.swing.JButton getBtnDelete() {
        return btnDelete;
    }

    public javax.swing.JButton getBtnList() {
        return btnList;
    }

    public javax.swing.JButton getBtnUpdate() {
        return btnUpdate;
    }

    public javax.swing.JButton getBtnUpdate2() {
        return btnUpdate2;
    }

    public javax.swing.JButton getBtnRegister2() {
        return btnRegister2;
    }

    public javax.swing.JButton getBtnRegister() {
        return btnRegister;
    }

    public javax.swing.JComboBox getCbCustomers() {
        return cbCustomers;
    }

    public javax.swing.JTable getTableCustomers() {
        return tableCustomers;
    }

    public javax.swing.JTextField getTxtAddress() {
        return txtAddress;
    }

    public javax.swing.JTextField getTxtId() {
        return txtId;
    }

    public javax.swing.JTextField getTxtLastName() {
        return txtLastName;
    }

    public javax.swing.JTextField getTxtName() {
        return txtName;
    }

    public javax.swing.JTextField getTxtTelephone() {
        return txtTelephone;
    }

    public javax.swing.JTextField getTxtFind() {
        return txtFind;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlButtons = new javax.swing.JPanel();
    btnDelete = new javax.swing.JButton();
    btnUpdate = new javax.swing.JButton();
    btnList = new javax.swing.JButton();
    btnRegister = new javax.swing.JButton();
    pnlMain = new javax.swing.JPanel();
    pnlCustomers = new javax.swing.JPanel();
    lblTittleList = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableCustomers = new javax.swing.JTable();
    lblFind = new javax.swing.JLabel();
    cbCustomers = new javax.swing.JComboBox();
    txtFind = new javax.swing.JTextField();
    pnlRegister = new javax.swing.JPanel();
    lblTittleRegister = new javax.swing.JLabel();
    lblId = new javax.swing.JLabel();
    txtId = new javax.swing.JTextField();
    lblName = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    lblLastName = new javax.swing.JLabel();
    txtLastName = new javax.swing.JTextField();
    lblAddress = new javax.swing.JLabel();
    txtAddress = new javax.swing.JTextField();
    lblTelephone = new javax.swing.JLabel();
    txtTelephone = new javax.swing.JTextField();
    btnRegister2 = new javax.swing.JButton();
    btnUpdate2 = new javax.swing.JButton();
    lblWarning = new javax.swing.JLabel();
    lblWarning1 = new javax.swing.JLabel();
    lblWarning2 = new javax.swing.JLabel();
    lblWarning3 = new javax.swing.JLabel();
    lblWarning4 = new javax.swing.JLabel();

    setClosable(true);

    pnlButtons.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

    btnDelete.setText("Eliminar");

    btnUpdate.setText("Actualizar");

    btnList.setText("Ver");

    btnRegister.setText("Registrar");

    javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
    pnlButtons.setLayout(pnlButtonsLayout);
    pnlButtonsLayout.setHorizontalGroup(
      pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlButtonsLayout.createSequentialGroup()
        .addGap(137, 137, 137)
        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlButtonsLayout.setVerticalGroup(
      pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlButtonsLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(pnlButtonsLayout.createSequentialGroup()
            .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );

    pnlMain.setLayout(new java.awt.CardLayout());

    pnlCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    lblTittleList.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    lblTittleList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTittleList.setText("Clientes Registrados");

    tableCustomers.setAutoCreateRowSorter(true);
    tableCustomers.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "CEDULA", "NOMBRE", "APELLIDO", "DIRECCION", "TELEFONO"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tableCustomers);

    lblFind.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    lblFind.setText("BUSCAR POR: ");

    cbCustomers.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    cbCustomers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CEDULA", "NOMBRE", "APELLIDO", " " }));

    txtFind.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    javax.swing.GroupLayout pnlCustomersLayout = new javax.swing.GroupLayout(pnlCustomers);
    pnlCustomers.setLayout(pnlCustomersLayout);
    pnlCustomersLayout.setHorizontalGroup(
      pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 667, Short.MAX_VALUE)
      .addGroup(pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlCustomersLayout.createSequentialGroup()
          .addGap(61, 61, 61)
          .addGroup(pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTittleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCustomersLayout.createSequentialGroup()
              .addComponent(lblFind)
              .addGap(4, 4, 4)
              .addComponent(cbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(txtFind)))
          .addGap(61, 61, 61))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomersLayout.createSequentialGroup()
          .addContainerGap(27, Short.MAX_VALUE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(25, 25, 25)))
    );
    pnlCustomersLayout.setVerticalGroup(
      pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 333, Short.MAX_VALUE)
      .addGroup(pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlCustomersLayout.createSequentialGroup()
          .addGap(20, 20, 20)
          .addComponent(lblTittleList)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(18, 18, 18)
          .addGroup(pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblFind)
            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    pnlMain.add(pnlCustomers, "card2");

    pnlRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    lblTittleRegister.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    lblTittleRegister.setText("Registrar Usuarios");

    lblId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    lblId.setText("Cédula: ");

    txtId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    lblName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    lblName.setText("Nombre: ");

    txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    lblLastName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    lblLastName.setText("Apellido: ");

    txtLastName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    lblAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    lblAddress.setText("Dirección: ");

    txtAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    lblTelephone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    lblTelephone.setText("Teléfono: ");

    txtTelephone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    btnRegister2.setText("Registrar");

    btnUpdate2.setText("Actualizar");

    lblWarning.setMaximumSize(new java.awt.Dimension(32, 32));
    lblWarning.setMinimumSize(new java.awt.Dimension(32, 32));
    lblWarning.setPreferredSize(new java.awt.Dimension(32, 32));

    lblWarning1.setMaximumSize(new java.awt.Dimension(32, 32));
    lblWarning1.setMinimumSize(new java.awt.Dimension(32, 32));
    lblWarning1.setPreferredSize(new java.awt.Dimension(32, 32));

    lblWarning2.setMaximumSize(new java.awt.Dimension(32, 32));
    lblWarning2.setMinimumSize(new java.awt.Dimension(32, 32));
    lblWarning2.setPreferredSize(new java.awt.Dimension(32, 32));

    lblWarning3.setMaximumSize(new java.awt.Dimension(32, 32));
    lblWarning3.setMinimumSize(new java.awt.Dimension(32, 32));
    lblWarning3.setPreferredSize(new java.awt.Dimension(32, 32));

    lblWarning4.setMaximumSize(new java.awt.Dimension(32, 32));
    lblWarning4.setMinimumSize(new java.awt.Dimension(32, 32));
    lblWarning4.setPreferredSize(new java.awt.Dimension(32, 32));

    javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
    pnlRegister.setLayout(pnlRegisterLayout);
    pnlRegisterLayout.setHorizontalGroup(
      pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(lblTittleRegister)
        .addGap(218, 218, 218))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlRegisterLayout.createSequentialGroup()
            .addContainerGap(477, Short.MAX_VALUE)
            .addComponent(btnUpdate2)
            .addGap(18, 18, 18))
          .addGroup(pnlRegisterLayout.createSequentialGroup()
            .addGap(82, 82, 82)
            .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(lblLastName)
              .addComponent(lblAddress)
              .addComponent(lblId)
              .addComponent(lblName)
              .addComponent(lblTelephone))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
              .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtId)
              .addComponent(txtName)
              .addComponent(txtTelephone))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnRegister2))
        .addContainerGap())
    );
    pnlRegisterLayout.setVerticalGroup(
      pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlRegisterLayout.createSequentialGroup()
        .addComponent(lblTittleRegister)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblId)
          .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblName)
          .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblLastName)
          .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblAddress)
          .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTelephone)
          .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblWarning4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnRegister2)
          .addComponent(btnUpdate2))
        .addContainerGap())
    );

    pnlMain.add(pnlRegister, "card3");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnList;
  private javax.swing.JButton btnRegister;
  private javax.swing.JButton btnRegister2;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JButton btnUpdate2;
  private javax.swing.JComboBox cbCustomers;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblAddress;
  private javax.swing.JLabel lblFind;
  private javax.swing.JLabel lblId;
  private javax.swing.JLabel lblLastName;
  private javax.swing.JLabel lblName;
  private javax.swing.JLabel lblTelephone;
  private javax.swing.JLabel lblTittleList;
  private javax.swing.JLabel lblTittleRegister;
  private javax.swing.JLabel lblWarning;
  private javax.swing.JLabel lblWarning1;
  private javax.swing.JLabel lblWarning2;
  private javax.swing.JLabel lblWarning3;
  private javax.swing.JLabel lblWarning4;
  private javax.swing.JPanel pnlButtons;
  private javax.swing.JPanel pnlCustomers;
  private javax.swing.JPanel pnlMain;
  private javax.swing.JPanel pnlRegister;
  private javax.swing.JTable tableCustomers;
  private javax.swing.JTextField txtAddress;
  private javax.swing.JTextField txtFind;
  private javax.swing.JTextField txtId;
  private javax.swing.JTextField txtLastName;
  private javax.swing.JTextField txtName;
  private javax.swing.JTextField txtTelephone;
  // End of variables declaration//GEN-END:variables

}
